INSERT INTO Estabelecimento VALUES ('Balada Digital')
INSERT INTO Cardapio VALUES (1)
INSERT INTO ItemCardapio VALUES (2.00, 'coca-cola', 'refrigerante', 1)
INSERT INTO TipoFuncionario VALUES ('Atendente')
INSERT INTO TipoFuncionario VALUES ('Caixa')
INSERT INTO TipoFuncionario VALUES ('Gerente')
INSERT INTO TipoFuncionario VALUES ('Recepcionista')
INSERT INTO Funcionario VALUES ('Pedro', 1, 1)
INSERT INTO Funcionario VALUES ('Luiz', 2, 1)
INSERT INTO Conta VALUES ('Conta criada para teste')
INSERT INTO Pedido VALUES (1)
INSERT INTO Pedido VALUES (1)
INSERT INTO ItemPedido VALUES (5, 1, 1)
INSERT INTO ItemPedido VALUES (5, 1, 2)
INSERT INTO Cliente VALUES (1,NULL,NULL,'Fulano','24326546174',1)
