insert into cardapio values (1)
insert into cliente values (1,1,null,1,null,2)
insert into conta values('Conta criada para teste')
insert into estabelecimento values ('Balada Digital')
insert into funcionario values ('João Paulo',1,1)
insert into funcionario values ('Maria',2,1)
insert into funcionario values ('Rosa',3,1)
insert into funcionario values ('Ronaldo',4,1)
insert into identificacao values ('22a',null,1)
insert into itemcardapio values (3.50,'Água sem gás',NULL,1)
insert into itemcardapio values (10.00,'Caipirinha de pinga',NULL,1)
insert into itemcardapio values (7.50,'Porçao de fritas','A porção de fritas pesa em torno de 600 gramas',1)
insert into itemcardapio values (8.00,'Porção de mandioca','A porção de mandioca pesa 750 gramas',1)
insert into itemcardapio values (5.00,'Refrigerante',NULL,1)
insert into itemcardapio values (6.50,'Bauru','O Bauru é feio com um queijo especial',1)
insert into itemcardapio values (7.00,'X - Salada',NULL,1)
insert into itempedido values (2,5,1)
insert into itempedido values (1,3,1)
insert into itempedido values (1,2,2)
insert into itempedido values (1,4,2)
insert into pedido values (1)
insert into pedido values (1)
insert into tipocliente values ('Individual')
insert into tipocliente values ('Mesa')
insert into tipofuncionario values ('Atendente')
insert into tipofuncionario values ('Caixa')
insert into tipofuncionario values ('Gerente')
insert into tipofuncionario values ('Recepcionista')
insert into tipoidentificacao values ('Mesa')
insert into tipoidentificacao values ('Impressão Digital')
	


